#!/usr/bin/env bash
set -euo pipefail
echo "[init-dongle] Initializing GSM dongle…"

ASTERISK_ETC_DIR="${ASTERISK_ETC_DIR:-/etc/asterisk}"
DONGLE_ID="${DONGLE_ID:-dongle0}"
AT_CANDIDATES="${AT_CANDIDATES:-/dev/ttyUSB2 /dev/ttyUSB1 /dev/ttyUSB0 /dev/ttyUSB3 /dev/ttyUSB4}"
AUDIO_CANDIDATES="${AUDIO_CANDIDATES:-/dev/ttyUSB3 /dev/ttyUSB2 /dev/ttyUSB1 /dev/ttyUSB0 /dev/ttyUSB4}"
DONGLE_CONF="${ASTERISK_ETC_DIR}/dongle.conf"

detect_at_port() {
  echo "[init-dongle] Probing AT port candidates: ${AT_CANDIDATES}"
  for dev in ${AT_CANDIDATES}; do
    if [ -e "$dev" ]; then
      echo -n "AT" > "$dev" || true
      if timeout 1s head -c 256 < "$dev" 2>/dev/null | tr -d '\r' | grep -qi "OK"; then
        echo "$dev"
        return 0
      fi
    fi
  done
  return 1
}

AT_PORT="$(detect_at_port || true)"
if [ -z "${AT_PORT:-}" ]; then
  echo "[init-dongle][ERROR] No AT port found. Ensure /dev/ttyUSB* devices are mapped."
  exit 1
fi
echo "[init-dongle] AT port: ${AT_PORT}"

AUDIO_PORT=""
for dev in ${AUDIO_CANDIDATES}; do
  if [ -e "$dev" ] && [ "$dev" != "$AT_PORT" ]; then
    AUDIO_PORT="$dev"; break
  fi
done
[ -z "${AUDIO_PORT}" ] && AUDIO_PORT="${AT_PORT}"
echo "[init-dongle] Audio port: ${AUDIO_PORT}"

mkdir -p "${ASTERISK_ETC_DIR}"
cat > "${DONGLE_CONF}" <<EOF
; --- Generated by init-dongle.sh ---
[general]
interval=30

[${DONGLE_ID}]
audio=${AUDIO_PORT}
data=${AT_PORT}
context=from-trunk
group=0
rxgain=0
txgain=0
autodeletesms=yes
EOF

# Quick health check
echo -n "AT+CPIN?" > "${AT_PORT}" || true
timeout 1s head -c 256 < "${AT_PORT}" 2>/dev/null || true

echo "[init-dongle] Wrote ${DONGLE_CONF}"
